#!/bin/bash

countries=("Albania" "Greece" "Portugal" "Argentina" "Hong_Kong" "Romania"
"Australia" "Hungary" "Serbia" "Austria" "Iceland" "Singapore" "Belgium" "India" "Slovakia"
"Bosnia_And_Herzegovina" "Indonesia" "Slovenia" "Brazil" "Ireland" "South_Africa"
"Bulgaria" "Israel" "South_Korea" "Canada" "Italy" "Spain" "Chile" "Japan" "Sweden"
"Costa_Rica" "Latvia" "Switzerland" "Croatia" "Luxembourg" "Taiwan" "Cyprus" "Malaysia" "Thailand"
"Czech_Republic" "Mexico" "Turkey" "Denmark" "Moldova" "Ukraine" "Estonia" "Netherlands" "United_Kingdom"
"Finland" "New_Zealand" "United_States" "France" "North_Macedonia" "Vietnam" "Georgia" "Norway" "Germany" "Poland")
 
while true # [ 1 ]
do
    
    rand=$[$RANDOM % ${#countries[@]}]
    nordvpn connect ${countries[$rand]}
    
    myIp="$(curl ifconfig.me)"
    echo "Meu ip agora é: ${myIp}"
    
    sleep $([[ $1 ]] && echo $1 || echo 60) 

done
